[package]
name = "server"
version = "0.0.48"
edition = "2021"
build = "src/build.rs"

[dependencies]
aes-gcm = "0.10.*"
anyhow = "1.0.*"
async-trait = "0.1.*"
axum = "0.6.20"
axum-server = { version = "0.5.1", features = ["tls-rustls", "tokio-rustls"] }
bcrypt = "0.15.0"
blake3 = "1.5.0"
byte-unit = "4.0.19"
bytes = "1.5.0"
chrono = "0.4.*"
clap = { version = "4.4.7", features = ["derive"] }
figlet-rs = "0.1.5"
figment = { version = "0.10.*", features = ["json", "toml", "env"] }
flume = "0.11.0"
futures = "0.3.*"
iggy = { path = "../iggy" }
jsonwebtoken = "9.0.0"
prometheus-client = "0.22.0"
quinn = "0.10.*"
rcgen = "0.11.*"
ring = "0.17.*"
rmp-serde = "1.1.2"
rustls = { version = "0.21.*", features = ["dangerous_configuration", "quic"] }
rustls-pemfile = "1.0.3"
serde = { version = "1.0.*", features = ["derive", "rc"] }
serde_json = "1.0.*"
serde_with = { version = "3.3.0", features = ["base64"] }
sled = "0.34.7"
strip-ansi-escapes = "0.2.0"
sysinfo = "0.29.*"
thiserror = "1.0.*"
tokio = { version = "1.33.0", features = ["full"] }
tokio-native-tls = "0.3.1"
tokio-rustls = "0.24.1"
toml = "0.8.*"
tower = { version = "0.4.13" }
tower-http = { version = "0.4.0", features = [
    "add-extension",
    "cors",
    "trace",
] }
tower-layer = "0.3.2"
tower-service = "0.3.2"
tracing = { version = "0.1.*" }
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.17", features = ["fmt"] }
uuid = { version = "1.5.0", features = ["v4", "fast-rng", "zerocopy"] }
xxhash-rust = { version = "0.8.*", features = ["xxh32"] }

[dev-dependencies]
libc = "0.2.147"

[build-dependencies]
vergen = { version = "8.2.*", features = [
    "build",
    "cargo",
    "git",
    "gitcl",
    "rustc",
] }

[[bin]]
name = "iggy-server"
path = "src/main.rs"
