[package]
name = "bench"
version = "0.0.1"
edition = "2021"

[dependencies]
async-trait = "0.1.68"
bytes = "1.4.0"
clap = { version = "4.1.11", features = ["derive"] }
derive_more = "0.99.17"
figlet-rs = "0.1.5"
futures = "0.3.28"
iggy = { path = "../iggy" }
integration = { path = "../integration" }
nonzero_lit = "0.1.2"
quinn = "0.10.0"
rustls = { version = "0.21.1", features = ["dangerous_configuration", "quic"] }
serde = { version = "1.0.189", features = ["derive"] }
thiserror = "1.0.40"
tokio = { version = "1.28.2", features = ["full"] }
toml = "0.8.4"
tracing = { version = "0.1.37" }
tracing-subscriber = { version = "0.3.16" }

[[bin]]
name = "iggy-bench"
path = "src/main.rs"
