[package]
name = "tools"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "data-seeder-tool"
path = "src/data-seeder/main.rs"

[dependencies]
anyhow = "1.0.70"
bytes = "1.4.0"
clap = { version = "4.1.11", features = ["derive"] }
iggy = { path = "../iggy" }
rand = "0.8.5"
thiserror = "1.0.40"
tokio = { version = "1.28.2", features = ["full"] }
tracing = { version = "0.1.37" }
tracing-subscriber = { version = "0.3.16" }
