[package]
name = "integration"
version = "0.0.1"
edition = "2021"

[dependencies]
assert_cmd = "2.0.12"
async-trait = "0.1.68"
byte-unit = "4.0.19"
bytes = "1.4.0"
derive_more = "0.99.17"
futures = "0.3.28"
humantime = "2.1.0"
iggy = { path = "../iggy", features = ["iggy-cmd"] }
libc = "0.2.147"
predicates = "3.0.3"
serial_test = "2.0.0"
server = { path = "../server" }
sled = "0.34.7"
tokio = { version = "1.28.2", features = ["full"] }
uuid = { version = "1.3.3", features = ["v4", "fast-rng", "zerocopy"] }
